/**
 * Fonte canônica da C3: a conversa de 07/12/2025, literal.
 *
 * Nada aqui é inferido, reescrito ou acrescentado. A única mídia é a fotografia
 * canônica, enviada em algum ponto entre 11:22:48 e 21:10:10 — intervalo em que
 * Pedro e Mabel estavam juntos presencialmente. O horário dela não foi
 * estabelecido, então o evento simplesmente não tem `time`.
 */

export type Author = "pedro" | "mabel";

export type ChatEvent =
  | { kind: "text"; author: Author; time: string; text: string }
  | { kind: "photo"; author: Author };

export const CONVERSATION_DATE = "7 de dezembro de 2025";

/** Nome do contato exatamente como aparece na conversa. */
export const CONTACT_NAME = "Mabel \u{1F339}";

export const chat: ChatEvent[] = [
  { kind: "text", author: "pedro", time: "06:47:31", text: "Bom dia meu amooorrr" },
  { kind: "text", author: "mabel", time: "06:48:58", text: "Bom dia mb" },
  { kind: "text", author: "pedro", time: "06:49:06", text: "Dormiu bem???" },
  { kind: "text", author: "mabel", time: "06:49:26", text: "Dmsss" },
  { kind: "text", author: "mabel", time: "06:49:29", text: "E vc?" },
  { kind: "text", author: "pedro", time: "06:49:31", text: "Uhuuulll" },
  { kind: "text", author: "pedro", time: "06:49:33", text: "Que bomm" },
  { kind: "text", author: "pedro", time: "06:49:36", text: "Eu também" },
  { kind: "text", author: "pedro", time: "06:49:39", text: "Hj sonhei com você" },
  { kind: "text", author: "mabel", time: "06:49:44", text: "Qbom amor" },
  { kind: "text", author: "mabel", time: "06:49:51", text: "Conta" },
  { kind: "text", author: "pedro", time: "06:50:02", text: "Eu não lembro" },
  { kind: "text", author: "mabel", time: "06:50:08", text: "Aa" },
  { kind: "text", author: "mabel", time: "06:50:56", text: "Tô com muita preguiça de ir lavar o cabelo" },
  { kind: "text", author: "pedro", time: "06:52:03", text: "Mas vc passou mto óleo ontem" },
  { kind: "text", author: "pedro", time: "06:52:11", text: "Se não lavar, não vai ficar oleoso?" },
  { kind: "text", author: "mabel", time: "06:52:24", text: "Uhum" },
  { kind: "text", author: "pedro", time: "06:53:14", text: "Então tem que lavar gatinha" },
  { kind: "text", author: "mabel", time: "06:53:25", text: "Ee" },
  { kind: "text", author: "mabel", time: "06:53:30", text: "Vou ir lá" },
  { kind: "text", author: "mabel", time: "06:53:35", text: "Beijinhos" },
  { kind: "text", author: "pedro", time: "06:53:36", text: "Okok" },
  { kind: "text", author: "pedro", time: "06:53:41", text: "Beijoes amoorr" },
  { kind: "text", author: "pedro", time: "06:53:43", text: "Eu te amo vius" },
  { kind: "text", author: "mabel", time: "06:53:49", text: "Eu tbm te amo" },
  { kind: "text", author: "pedro", time: "09:37:01", text: "Oh meu amorr" },
  { kind: "text", author: "pedro", time: "09:37:05", text: "Tô saindo de casa viuuss" },
  { kind: "text", author: "pedro", time: "09:37:09", text: "Eu te amo" },
  { kind: "text", author: "mabel", time: "09:37:34", text: "Okok" },
  { kind: "text", author: "mabel", time: "09:37:39", text: "Eu tbm te amooo" },
  { kind: "text", author: "mabel", time: "09:37:46", text: "Vou finalizar meu hair agora" },
  { kind: "text", author: "pedro", time: "11:01:04", text: "Amor, daqui uns 15 minutos eu chego aí" },
  { kind: "text", author: "mabel", time: "11:01:21", text: "Nosso Deus" },
  { kind: "text", author: "mabel", time: "11:01:22", text: "Okok" },
  { kind: "text", author: "pedro", time: "11:02:57", text: "Oq??" },
  { kind: "text", author: "mabel", time: "11:04:10", text: "Pensei que ia chegar cedo" },
  { kind: "text", author: "pedro", time: "11:04:18", text: "Oh gatinha" },
  { kind: "text", author: "pedro", time: "11:04:23", text: "É o horário do ônibus" },
  { kind: "text", author: "pedro", time: "11:04:28", text: "Eu peguei ele 10h" },
  { kind: "text", author: "pedro", time: "11:04:32", text: "Já era pra tá chegando msm" },
  { kind: "text", author: "mabel", time: "11:04:41", text: "Tudo bem" },
  { kind: "text", author: "mabel", time: "11:18:37", text: "Tá chegando???" },
  { kind: "text", author: "pedro", time: "11:22:48", text: "Já cheguei" },
  { kind: "photo", author: "pedro" },
  { kind: "text", author: "pedro", time: "21:10:10", text: "Oiii meu amoorr" },
  { kind: "text", author: "pedro", time: "21:10:12", text: "Cheguei vius" },
  { kind: "text", author: "mabel", time: "21:10:41", text: "Qbom amor" },
  { kind: "text", author: "pedro", time: "21:11:53", text: "Tá tudo bem aí??" },
  { kind: "text", author: "mabel", time: "21:13:01", text: "Acho que sim" },
  { kind: "text", author: "mabel", time: "21:13:09", text: "E aí?" },
  { kind: "text", author: "mabel", time: "21:13:21", text: "Perdão por hoje" },
  { kind: "text", author: "mabel", time: "21:13:45", text: "Por eu ter passado a maior parte do tempo irritada" },
  { kind: "text", author: "mabel", time: "21:13:55", text: "E tudo mais" },
  { kind: "text", author: "pedro", time: "21:13:56", text: "Ta tudo ótimo amor" },
  { kind: "text", author: "mabel", time: "21:23:00", text: "Eu queria ter ficado mais abraçada com você" },
  { kind: "text", author: "pedro", time: "21:23:05", text: "Eu também" },
  { kind: "text", author: "pedro", time: "21:23:14", text: "Acho que foi o melhor abraço que já demos" },
  { kind: "text", author: "mabel", time: "21:23:24", text: "Qual" },
  { kind: "text", author: "pedro", time: "21:23:35", text: "Quando você chorou" },
  { kind: "text", author: "mabel", time: "21:23:53", text: "Esquece isso" },
  { kind: "text", author: "pedro", time: "21:23:57", text: "Eu não" },
  { kind: "text", author: "pedro", time: "21:24:09", text: "Eu fiquei feliz que você conseguiu chorar dessa vez" },
  { kind: "text", author: "pedro", time: "21:24:16", text: "Ao invés de só reprimir" },
  { kind: "text", author: "mabel", time: "21:24:35", text: "Não gostei" },
  { kind: "text", author: "pedro", time: "21:24:40", text: "Pq amor?" },
  { kind: "text", author: "mabel", time: "21:24:49", text: "Foi bom só a parte de estar com você" },
  { kind: "text", author: "mabel", time: "21:25:06", text: "Pq aí eu fico parecendo sla" },
  { kind: "text", author: "mabel", time: "21:25:11", text: "Dramática" },
  { kind: "text", author: "pedro", time: "21:25:14", text: "Não amor" },
  { kind: "text", author: "pedro", time: "21:25:21", text: "Esquece isso" },
  { kind: "text", author: "pedro", time: "21:25:28", text: "Eu te entendo" },
  { kind: "text", author: "pedro", time: "21:25:38", text: "E você pode só se soltar comigo" },
  { kind: "text", author: "pedro", time: "21:25:45", text: "Eu vou enxugar todas as suas lágrimas" },
  { kind: "text", author: "pedro", time: "21:25:57", text: "Eu te amo, tá?" },
  { kind: "text", author: "mabel", time: "21:26:02", text: "Eu sei que posso" },
  { kind: "text", author: "mabel", time: "21:26:07", text: "Mas não gosto" },
  { kind: "text", author: "mabel", time: "21:26:13", text: "Eu tbm te amo" },
  { kind: "text", author: "pedro", time: "21:30:38", text: "Eu te amo" },
  { kind: "text", author: "pedro", time: "21:30:40", text: "Muito" },
  { kind: "text", author: "pedro", time: "21:30:45", text: "E eu tô mto orgulhoso de você" },
  { kind: "text", author: "mabel", time: "21:30:46", text: "Eu tbm te amo muito" },
  { kind: "text", author: "pedro", time: "21:30:47", text: "Por tudo" },
  { kind: "text", author: "mabel", time: "21:31:01", text: "Obrigada amor" },
  { kind: "text", author: "mabel", time: "21:31:06", text: "Muito obrigada" },
  { kind: "text", author: "pedro", time: "21:31:13", text: "Não precisa agradecer" },
  { kind: "text", author: "pedro", time: "21:31:21", text: "Você faz por merecer gatinha" },
  { kind: "text", author: "pedro", time: "21:31:34", text: "Agr eu vou lá" },
  { kind: "text", author: "pedro", time: "21:31:36", text: "Bjsss" },
  { kind: "text", author: "mabel", time: "21:31:49", text: "Mas você é o único que percebe" },
  { kind: "text", author: "mabel", time: "21:31:53", text: "Beijinhos" },
  { kind: "text", author: "mabel", time: "21:59:04", text: "Você me perdoa?" },
  { kind: "text", author: "pedro", time: "21:59:09", text: "Uai amor" },
  { kind: "text", author: "pedro", time: "21:59:12", text: "Pelo que?" },
  { kind: "text", author: "mabel", time: "21:59:24", text: "Por eu estar assim" },
  { kind: "text", author: "mabel", time: "21:59:55", text: "Não é legal ficar conversando com uma pessoa que só fala/faz coisas depressivas" },
  { kind: "text", author: "pedro", time: "22:00:06", text: "Meu amor" },
  { kind: "text", author: "pedro", time: "22:00:08", text: "Tá tudo bem" },
  { kind: "text", author: "pedro", time: "22:00:25", text: "Para de achar que suas atitudes são um incômodo" },
  { kind: "text", author: "mabel", time: "22:00:38", text: "Algumas são" },
  { kind: "text", author: "mabel", time: "22:00:48", text: "Essa é uma delas" },
  { kind: "text", author: "pedro", time: "22:00:53", text: "Não amkr" },
  { kind: "text", author: "pedro", time: "22:00:58", text: "Tá tudo bem" },
  { kind: "text", author: "pedro", time: "22:01:13", text: "Você não precisa se preocupar com isso, tá bom?" },
  { kind: "text", author: "pedro", time: "22:01:18", text: "Se você estiver triste" },
  { kind: "text", author: "pedro", time: "22:01:21", text: "Eu prefiro que fale" },
  { kind: "text", author: "mabel", time: "22:01:34", text: "Eu tô" },
  { kind: "text", author: "pedro", time: "22:01:48", text: "E você quer falar sobre isso?" },
  { kind: "text", author: "mabel", time: "22:01:57", text: "Não sei oq falar" },
  { kind: "text", author: "pedro", time: "22:02:10", text: "Só fala o que você tá pensando" },
  { kind: "text", author: "pedro", time: "22:02:15", text: "Ou tá sentindo" },
  { kind: "text", author: "mabel", time: "22:02:52", text: "Tô pensando no quanto foi bom ficar abraçada com você enquanto eu estava mal" },
  { kind: "text", author: "mabel", time: "22:03:10", text: "E não sei oq sinto agora" },
  { kind: "text", author: "mabel", time: "22:06:41", text: "Você é incrível" },
  { kind: "text", author: "mabel", time: "22:06:49", text: "E eu me sinto bem ao seu lado" },
  { kind: "text", author: "pedro", time: "22:10:26", text: "Fico mto feliz por isso amor" },
  { kind: "text", author: "pedro", time: "22:10:33", text: "Tudo que eu puder fazer pra te ajudar" },
  { kind: "text", author: "pedro", time: "22:10:38", text: "Mesmo que seja só um pouco" },
  { kind: "text", author: "pedro", time: "22:10:40", text: "Eu vou fazer" },
  { kind: "text", author: "pedro", time: "22:10:45", text: "Favoritei" },
  { kind: "text", author: "pedro", time: "22:35:45", text: "Eu te amo, tá bom?" },
  { kind: "text", author: "mabel", time: "22:35:53", text: "Eu tbm te amo" },
  { kind: "text", author: "pedro", time: "22:36:01", text: "Sempre que estiver triste" },
  { kind: "text", author: "pedro", time: "22:36:07", text: "E eu estiver por perto" },
  { kind: "text", author: "pedro", time: "22:36:12", text: "Me procura" },
  { kind: "text", author: "pedro", time: "22:36:19", text: "Faço questão de parar tudo pra te abraçar" },
  { kind: "text", author: "mabel", time: "22:36:34", text: "Obrigada" },
  { kind: "text", author: "mabel", time: "22:36:43", text: "Você é muito pra mim" },
  { kind: "text", author: "mabel", time: "22:36:58", text: "Não sei como retribuir tanto afeto assim" },
  { kind: "text", author: "pedro", time: "22:37:06", text: "Nada amor" },
  { kind: "text", author: "pedro", time: "22:37:13", text: "Você não merece menos que isso" },
  { kind: "text", author: "pedro", time: "22:37:24", text: "Você já retribui gatinha" },
  { kind: "text", author: "mabel", time: "22:37:47", text: "Mesmo assim" },
  { kind: "text", author: "mabel", time: "22:37:54", text: "Você é incrível" },
  { kind: "text", author: "mabel", time: "22:38:04", text: "E eu gosto muito de você" },
  { kind: "text", author: "pedro", time: "22:38:11", text: "Que bommm gatinha" },
  { kind: "text", author: "pedro", time: "22:38:14", text: "Eu também gosto mto de você" },
  { kind: "text", author: "pedro", time: "22:38:17", text: "Tipo mto msm" },
  { kind: "text", author: "mabel", time: "22:38:31", text: "E me senti muito bem em ficar com você em um momento ruim" },
  { kind: "text", author: "mabel", time: "22:38:41", text: "Qbomm" },
  { kind: "text", author: "pedro", time: "22:38:51", text: "Fico feliz amor" },
  { kind: "text", author: "pedro", time: "22:39:03", text: "Eu sempre vou estar aqui pra isso" },
  { kind: "text", author: "mabel", time: "22:39:24", text: "Agradeço por isso" },
  { kind: "text", author: "pedro", time: "22:39:37", text: "Não precisa agradecer amooorr" },
  { kind: "text", author: "mabel", time: "22:39:48", text: "Mas eu queroo" },
  { kind: "text", author: "pedro", time: "22:39:54", text: "Te ver bem já é muito mais que o suficiente" },
  { kind: "text", author: "mabel", time: "22:40:11", text: "Tudo bem" },
  { kind: "text", author: "mabel", time: "22:41:52", text: "Me conta alguma coisa?" },
  { kind: "text", author: "pedro", time: "22:42:00", text: "Conto amor, claro" },
  { kind: "text", author: "pedro", time: "22:42:21", text: "Eu gostaria de dizer o quanto você é especial pra mim" },
  { kind: "text", author: "pedro", time: "22:42:31", text: "Você é maravilhosa amor" },
  { kind: "text", author: "pedro", time: "22:42:35", text: "Eu te amo muito" },
  { kind: "text", author: "pedro", time: "22:42:48", text: "Mesmo quando você tá emburrada" },
  { kind: "text", author: "pedro", time: "22:42:58", text: "Pq é mto legal te ver lentamente voltando ao normal" },
  { kind: "text", author: "mabel", time: "22:43:25", text: "Você tbm é muito especial pra mim" },
  { kind: "text", author: "mabel", time: "22:43:36", text: "E eu sou grata por te ter na minha vida" },
  { kind: "text", author: "mabel", time: "22:43:47", text: "Eu tbm te amo muito" },
  { kind: "text", author: "mabel", time: "22:43:54", text: "Kkkkkk" },
  { kind: "text", author: "pedro", time: "22:44:06", text: "E vai ser pelo resto da sua vida" },
  { kind: "text", author: "pedro", time: "22:44:13", text: "Pq eu não saio dela nem fudendo" },
  { kind: "text", author: "pedro", time: "22:44:23", text: "É sério" },
  { kind: "text", author: "pedro", time: "22:44:37", text: "Você fica tentando esconder que quer ficar abraçada" },
  { kind: "text", author: "pedro", time: "22:44:40", text: "Mas não consegue" },
  { kind: "text", author: "mabel", time: "22:44:57", text: "Graças a Deus" },
  { kind: "text", author: "mabel", time: "22:45:01", text: "Me deixaaaa" },
  { kind: "text", author: "pedro", time: "22:45:12", text: "Claro que deixo" },
  { kind: "text", author: "pedro", time: "22:45:15", text: "É engraçado" },
  { kind: "text", author: "pedro", time: "22:45:24", text: "Eu gosto mto de você" },
  { kind: "text", author: "pedro", time: "22:45:33", text: "Quero poder passar logo meus dias com você" },
  { kind: "text", author: "mabel", time: "22:45:50", text: "Vc tbm é muito engraçado" },
  { kind: "text", author: "mabel", time: "22:46:10", text: "Só de olhar pra vc já da vontade de rir kkkkk" },
  { kind: "text", author: "mabel", time: "22:46:20", text: "Tbm gosto muito de vc" },
  { kind: "text", author: "mabel", time: "22:46:30", text: "Espero por esse dia" },
  { kind: "text", author: "pedro", time: "22:47:59", text: "Poxa amor" },
  { kind: "text", author: "pedro", time: "22:48:06", text: "Eu amo a sensação de poder te ajudar" },
  { kind: "text", author: "pedro", time: "22:48:16", text: "De sentir que você tá sla" },
  { kind: "text", author: "pedro", time: "22:48:28", text: "Se entregando pra mim" },
  { kind: "text", author: "pedro", time: "22:48:32", text: "Pra eu poder cuidar de você" },
  { kind: "text", author: "mabel", time: "22:48:57", text: "E eu amo a sensação de ter você cuidando de mim" },
  { kind: "text", author: "mabel", time: "22:49:10", text: "É confortável" },
  { kind: "text", author: "mabel", time: "22:49:25", text: "Já me entreguei a muito tempo" },
  { kind: "text", author: "pedro", time: "22:49:38", text: "Que bommm amor" },
  { kind: "text", author: "pedro", time: "22:49:48", text: "Eu faco de tudo pra você se sentir confortável mesmo" },
  { kind: "text", author: "pedro", time: "22:51:00", text: "Fico feliz meu amor" },
  { kind: "text", author: "pedro", time: "22:51:05", text: "Você merece" },
  { kind: "text", author: "mabel", time: "22:51:21", text: "Aiai" },
  { kind: "text", author: "pedro", time: "22:51:32", text: "Gatinha" },
  { kind: "text", author: "mabel", time: "22:51:37", text: "Eu" },
  { kind: "text", author: "pedro", time: "22:51:43", text: "Você se importa se eu for dormir agora?" },
  { kind: "text", author: "mabel", time: "22:51:49", text: "Tudo bem" },
  { kind: "text", author: "mabel", time: "22:51:56", text: "Eu tbm vou" },
  { kind: "text", author: "pedro", time: "22:52:11", text: "Então vamos meu amor" },
  { kind: "text", author: "pedro", time: "22:52:16", text: "Dorme com Deus" },
  { kind: "text", author: "mabel", time: "22:52:17", text: "Boa noite amor" },
  { kind: "text", author: "mabel", time: "22:52:22", text: "Dorme com Deus tbm" },
  { kind: "text", author: "pedro", time: "22:52:23", text: "Até amanhã" },
  { kind: "text", author: "mabel", time: "22:52:25", text: "Até amanhã" },
  { kind: "text", author: "pedro", time: "22:52:29", text: "Eu te amooooooooooo" },
  { kind: "text", author: "mabel", time: "22:52:31", text: "Eu te amo muitooo" },
  { kind: "text", author: "mabel", time: "22:52:35", text: "💛" },
  { kind: "text", author: "pedro", time: "22:52:41", text: "Você é o amor da minha vida" },
  { kind: "text", author: "mabel", time: "22:52:55", text: "Você tbm é o amor da minha vida" },
];
